const metricsData = [
  {
    "Bain Media Input Score": "",
    "Content Score": 0.530555556,
    "Average rating \n(All SKU - Ever Rated)": 4.362742297,
    Reviews: "",
    "Net sentiment of reviews (All SKU - Incremental) (If data points>30)": 0.5739,
    "Availability%": 0.980515851,
    "Blended ROAS \n(Digital on plat spends - inc JBP and digital sales - inc organic)":
      "",
    "On platform Green spends %": "",
    "Cust ac rate %": "",
    "New Customers  (new to brand - absolute number / total consumer in the period)":
      "",
    "Search – Spends": "",
    Impressions: "",
    CPM: "",
    Clicks: "",
    CTR: "",
    CPC: "",
    Purchases: "",
    "Order Conversion Rate": "",
    "Click to new purchase": "",
    "% of new purchase rate": "",
    "Sales value": "",
    "unit sold": "",
    "Cost per order (new)": "",
    "ACOS %": "",
    "Display – Spends": "",
    Impressions__1: "",
    CPM__1: "",
    Clicks__1: "",
    CTR__1: "",
    CPC__1: "",
    DPV: "",
    DPVR: "",
    ATC: "",
    ATCR: "",
    Purchases__1: "",
    "Order Conversion Rate__1": "",
    "Click to new purchase__1": "",
    "% of new purchase rate__1": "",
    "Sales value__1": "",
    "unit sold__1": "",
    "Cost per new customer (CAC)": "",
    "ACOS %__1": "",
    "Search - Spends": "",
    Impressions__2: "",
    CPM__2: "",
    Clicks__2: "",
    CTR__2: "",
    CPC__2: "",
    Purchases__2: "",
    "Order Conversion Rate__2": "",
    "Sales value__2": "",
    "unit sold__2": "",
    "ACOS %__2": "",
    "Search - Spends__1": "",
    Impressions__3: "",
    CPM__3: "",
    Clicks__3: "",
    CTR__3: "",
    CPC__3: "",
    Purchases__3: "",
    "Order Conversion Rate__3": "",
    "Sales value__3": "",
    "unit sold__3": "",
    "ACOS %__3": "",
    "Search - Spends__2": "",
    Clicks__4: "",
    CPC__4: "",
    Purchases__4: "",
    "Order Conversion Rate__4": "",
    "Sales value__4": "",
    "unit sold__4": "",
    "ACOS %__4": "",
    "Search - Spends__3": "",
    Impressions__4: "",
    CPM__4: "",
    Clicks__5: "",
    CTR__4: "",
    CPC__5: "",
    Purchases__5: "",
    "Order Conversion Rate__5": "",
    "Click to new purchase__2": "",
    "% of new purchase rate__2": "",
    "Sales value__5": "",
    "unit sold__5": "",
    "Cost per order (new)__1": "",
    "ACOS %__5": "",
    "Search - home page banners": "",
    Impressions__5: "",
    CPM__5: "",
    Clicks__6: "",
    CTR__5: "",
    Order: "",
    "Order Conversion Rate__6": "",
    "ACOS %(to be calculated )": "",
    "Search - home page banners__1": "",
    Impressions__6: "",
    CPM__6: "",
    Clicks__7: "",
    CTR__6: "",
    Order__1: "",
    "Order Conversion Rate__7": "",
    "ACOS %(to be calculated )__1": "",
    "Relative pricing adherance": "",
    "Search visibility share \n(Organic)": 0.057421875,
    "Search visibility share \n(Paid)": 0.003079028,
    "Market Share - Amazon": "",
    "Market share - FK": "",
    "Market share - BB": "",
    "Market share - Grofers / Blinkit": "",
    "Market share - Nykaa": "",
    "Market share - Myntra": "",
    "Amazon Best seller rank": 0.013,
    "Organic rank on top keywords": 5.78,
    "SEO (SEO optimer)": "B",
    "Net sentiment": 0.3514,
    Mentions: 2646,
    Engagement: 21789,
    "Engagement %": 0.04,
    "Number of queries": "",
    "% of queries & negative mentions responded to": "",
    "SLA of response time": "",
    "ROI %": "",
    Conversion: "",
    Engagement__1: "",
    CPV: "",
    Views: "",
    "50% of budgets to cohorts": "",
    "BLS FB": "",
    "BLS YT/JIO/Hotstar/Airtel": "",
    "Off Platform green spends %": "",
    Spends: "",
    Impressions__7: "",
    Reach: "",
    Frequency: "",
    Clicks__8: "",
    VTR: "",
    CPM__7: "",
    "Add to cart": "",
    "Click to cart %": "",
    "Cart to checkout": "",
    Transactions: "",
    "Transaction rate": "",
    "Cost per transaction": "",
    AOV: "",
    "ACOS %__6": "",
    Spends__1: "",
    Impressions__8: "",
    Reach__1: "",
    Frequency__1: "",
    Clicks__9: "",
    VTR__1: "",
    CPM__8: "",
    "Add to cart__1": "",
    "Click to cart %__1": "",
    "Cart to checkout__1": "",
    Transactions__1: "",
    "Transaction rate__1": "",
    "Cost per transaction__1": "",
    AOV__1: "",
    "ACOS %__7": "",
    Spends__2: "",
    Impressions__9: "",
    Reach__2: "",
    Frequency__2: "",
    Clicks__10: "",
    VTR__2: "",
    CPM__9: "",
    "Add to cart__2": "",
    "Click to cart %__2": "",
    "Cart to checkout__2": "",
    Transactions__2: "",
    "Transaction rate__2": "",
    "Cost per transaction__2": "",
    AOV__2: "",
    "ACOS %__8": "",
    Spends__3: "",
    Impressions__10: "",
    Clicks__11: "",
    CPM__10: "",
    CTR__7: "",
    "Add to cart__3": "",
    "Click to cart %__3": "",
    "Cart to checkout__3": "",
    Transactions__3: "",
    "Transaction rate__3": "",
    "Cost per transaction__3": "",
    AOV__3: "",
    "ACOS %__9": "",
    Spends__4: "",
    Impressions__11: "",
    Clicks__12: "",
    CPM__11: "",
    VTR__3: "",
    CTR__8: "",
    "Add to cart__4": "",
    "Click to cart %__4": "",
    "Cart to checkout__4": "",
    Transactions__4: "",
    "Transaction rate__4": "",
    "Cost per transaction__4": "",
    AOV__4: "",
    "ACOS %__10": "",
    Spends__5: "",
    Impressions__12: "",
    Clicks__13: "",
    CPC__6: "",
    CTR__9: "",
    "Add to cart__5": "",
    "Click to cart %__5": "",
    "Cart to checkout__5": "",
    Transactions__5: "",
    "Transaction rate__5": "",
    "Cost per transaction__5": "",
    AOV__5: "",
    "ACOS %__11": "",
    Spends__6: "",
    Impressions__13: "",
    Clicks__14: "",
    CPC__7: "",
    CTR__10: "",
    "Add to Cart": "",
    "Click to cart %__6": "",
    "Cart to checkout__6": "",
    Transactions__6: "",
    "Transaction rate__6": "",
    "Cost per transaction__6": "",
    AOV__6: "",
    "ACOS %__12": "",
    Spends__7: "",
    Impressions__14: "",
    Clicks__15: "",
    CPC__8: "",
    CTR__11: "",
    "Add to Cart__1": "",
    "Click to cart %__7": "",
    "Cart to checkout__7": "",
    Transactions__7: "",
    "Transaction rate__7": "",
    "Cost per transaction__7": "",
    AOV__7: "",
    "ACOS %__13": "",
    Spends__8: "",
    Impressions__15: "",
    CPM__12: "",
    Clicks__16: "",
    CPC__9: "",
    CTR__12: "",
    "Add to Cart__2": "",
    "Click to cart %__8": "",
    "Cart to checkout__8": "",
    Transactions__8: "",
    "Transaction rate__8": "",
    "Cost per transaction__8": "",
    AOV__8: "",
    "ACOS %__14": "",
    Spends__9: "",
    Impressions__16: "",
    CPM__13: "",
    Clicks__17: "",
    CPC__10: "",
    CTR__13: "",
    "Add to Cart__3": "",
    "Click to cart %__9": "",
    "Cart to checkout__9": "",
    Transactions__9: "",
    "Transaction rate__9": "",
    "Cost per transaction__9": "",
    AOV__9: "",
    "ACOS %__15": "",
    Spends__10: "",
    Impressions__17: "",
    CPM__14: "",
    Clicks__18: "",
    CPC__11: "",
    CTR__14: "",
    "Add to Cart__4": "",
    "Click to cart %__10": "",
    "Cart to checkout__10": "",
    Transactions__10: "",
    "Transaction rate__10": "",
    "Cost per transaction__10": "",
    AOV__10: "",
    "ACOS %__16": "",
    "Unique Visitors": "",
    Sessions: "",
    "Load Time (seconds)": "",
    "Pages per sessions": "",
    "Avg. Session Duration (mins)": "",
    "Product Views": "",
    "Add to Basket": "",
    Checkout: "",
    "Product views per session": "",
    "Sessions to product views %": "",
    "Product views to cart %": "",
    "Cart to Checkout %": "",
    "Check out to Transaction %": "",
    "Overall conversion %": "",
    AOV__11: "",
    "ACOS %__17": "",
    "Repeat rate %": "",
    CAC: "",
    NPS: "",
    "Mobile page speed insights score": 35,
    "Web page speed insights score": 87,
    "Largest contentful paint (LCP) - seconds": 11.4,
    "First input delay (FID) - milli seconds": 720,
    "Cumulative layout shift (CLS)": 0.003,
    "First contentful paint (FCP) - seconds": 1.8,
    "Time to interact (TTI)- seconds": 18.8,
    "Speed Index - seconds": 9.9,
    "Total blocking time (TBT) - milli seconds": "4,010",
    "GT metrics grade": "A",
    "Bounce rate": 0.6867,
    "Usability (SEO optimer)": "F",
    "Performance (SEO optimer)": "A-",
    "Social (SEO optimer)": "A+",
  },
];
export function getMetricData() {
  return metricsData;
}
